config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, path: '', path_names: { sign_in: 'login' } , controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  devise_scope :user do
    get 'sign_out', to: 'users/sessions#destroy'
  end
  root :to => 'web/dashboards#index'

  scope module: :web do
    resources :dashboards, only: :index
    resources :diets, except: :show do
      resources :weight_movements, except: :show
    end
    namespace :settings do
      resources :food_options, except: :show
    end
  end
end

app/models/weight_movement.rb
class WeightMovement < ApplicationRecord
  belongs_to :diet

  validates :weight, :reference_date, presence: true
end

app/controllers/web/weight_movements_controller.rb
class Web::WeightMovementsController < ApplicationController
  before_action :set_diet, only: [:index, :new, :create, :edit, :update, :destroy]
  before_action :set_weight_movement, only: [:edit, :update, :destroy]

  def index
    @weight_movements = @diet.weight_movements.order(reference_date: :desc)
  end

  def new
    @weight_movement = @diet.weight_movements.build
  end

  def create
    @weight_movement = @diet.weight_movements.build weight_movement_params

    if @weight_movement.save
      redirect_to diet_weight_movements_path(params[:diet_id]), notice: t('notices.created', model: WeightMovement.model_name.human)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @weight_movement.update(weight_movement_params)
      redirect_to diet_weight_movements_path(params[:diet_id]), notice: t('notices.updated', model: WeightMovement.model_name.human)
    else
      render :edit
    end
  end

  def destroy
    if @weight_movement.destroy
      redirect_to diet_weight_movements_path(params[:diet_id]), notice: t('notices.destroyed', model: WeightMovement.model_name.human)
    else
      redirect_to diet_weight_movements_path(params[:diet_id]), alert: t('notices.destroy_restricted', model: WeightMovement.model_name.human)
    end
  end

  private

  def set_diet
    @diet = current_user.diets.find(params[:diet_id])
  end

  def set_weight_movement
    @weight_movement = @diet.weight_movements.find(params[:id])
  end

  def weight_movement_params
    params.require(:weight_movement).permit(:weight, :reference_date)
  end
end

app/views/web/weight_movements/_form.html.erb
<%= render 'layouts/errors', resource: @weight_movement %>
<div class="pmd-card pmd-z-depth pmd-card-custom-form">
  <div class="pmd-card-body">
    <%= simple_form_for [@diet, @weight_movement] do |f| %>
      <%= f.input :reference_date, as: :string, input_html: { class: 'form-control datepicker',
                                                              value: "#{ f.object.reference_date.strftime("%d/%m/%Y") if f.object.reference_date.present? }" },
                  wrapper_html: { class: 'pmd-textfield col-md-6' } %>
      <%= f.input :weight, input_html: { class: 'form-control' },
      wrapper_html: { class: 'pmd-textfield col-md-6' } %>

      <%= render 'layouts/common/buttons/back', link: diet_weight_movements_path(@diet) %>
      <%= render 'layouts/common/buttons/submit' %>
    <% end %>
  </div>
</div>

app/views/web/weight_movements/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <%= render 'layouts/common/header', title: FoodOption.model_name.human(count: 2), subtitle: t('core.actions.edit') %>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/web/weight_movements/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <%= render 'layouts/common/header', title: WeightMovement.model_name.human(count: 2), subtitle: '' %>
      <ul class="list-group pmd-z-depth pmd-card-list pmd-list-icon">
        <% if @weight_movements.each do |weight_movement| %>
          <li class="list-group-item">
            <div class="media-body">
              <h3 class="list-group-item-heading">
                Peso: <%= weight_movement.weight %>
              </h3>
              <span class="list-group-item-text">
                <div>
                  Data: <%= weight_movement.reference_date.strftime("%d/%m/%Y") %>
                </div>
              </span>
            </div>

            <%= render 'layouts/common/icon_links/edit', link: edit_diet_weight_movement_path(@diet, weight_movement) %>
            <%= render 'layouts/common/icon_links/destroy', link: diet_weight_movement_path(@diet, weight_movement) %>
          </li>
        <% end.empty? %>
          <li class="list-group-item">
            <div class="media-body">
              <h3 class="list-group-item-heading">
                <%= t('core.empty') %>
              </h3>
            </div>
          </li>
        <% end %>
      </ul>

      <div id="list-action-buttons">
        <%= render 'layouts/common/buttons/new', link: new_diet_weight_movement_path %>
        <%= render 'layouts/common/buttons/back',
                   link: diets_path %>
      </div>
    </div>
  </div>
</div>

app/views/web/weight_movements/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <%= render 'layouts/common/header', title: WeightMovement.model_name.human(count: 2), subtitle: t('core.actions.add') %>
      <%= render 'form' %>
    </div>
  </div>
</div>