config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, path: '', path_names: { sign_in: 'login' } , controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  devise_scope :user do
    get 'sign_out', to: 'users/sessions#destroy'
  end
  root :to => 'web/dashboards#index'

  scope module: :web do
    resources :dashboards, only: :index
    resources :diets, except: :show do
      resources :weight_movements, except: :show
    end
    namespace :settings do
      resources :food_options, except: :show
    end
  end
end

app/models/food_option.rb
class FoodOption < ApplicationRecord
  belongs_to :user

  validates :description, presence: true

  def to_s
    description
  end
end

app/controllers/web/settings/food_options_controller.rb
class Web::Settings::FoodOptionsController < ApplicationController
  before_action :set_food_option, only: [:edit, :update, :destroy]

  def index
    @food_options = current_user.food_options
  end

  def new
    @food_option = current_user.food_options.build
  end

  def create
    @food_option = current_user.food_options.build food_option_params

    if @food_option.save
      redirect_to settings_food_options_path, notice: t('notices.created', model: FoodOption.model_name.human)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @food_option.update(food_option_params)
      redirect_to settings_food_options_path, notice: t('notices.updated', model: FoodOption.model_name.human)
    else
      render :edit
    end
  end

  def destroy
    if @food_option.destroy
      redirect_to settings_food_options_path, notice: t('notices.destroyed', model: FoodOption.model_name.human)
    else
      redirect_to settings_food_options_path, alert: t('notices.destroy_restricted', model: FoodOption.model_name.human)
    end
  end

  private

  def set_food_option
    @food_option = current_user.food_options.find(params[:id])
  end

  def food_option_params
    params.require(:food_option).permit(:description)
  end
end

app/views/web/settings/food_options/_form.html.erb
<%= render 'layouts/errors', resource: @food_option %>
<div class="pmd-card pmd-z-depth pmd-card-custom-form">
  <div class="pmd-card-body">
    <%= simple_form_for [:settings, @food_option] do |f| %>
      <%= f.input :description, input_html: { class: 'form-control' },
                  wrapper_html: { class: 'pmd-textfield' } %>

      <%= render 'layouts/common/buttons/back', link: settings_food_options_path %>
      <%= render 'layouts/common/buttons/submit' %>
    <% end %>
  </div>
</div>

app/views/web/settings/food_options/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <%= render 'layouts/common/header', title: FoodOption.model_name.human(count: 2), subtitle: '' %>
      <ul class="list-group pmd-z-depth pmd-card-list pmd-list-icon">
        <% if @food_options.each do |food_option| %>
          <li class="list-group-item">
            <div class="media-body">
              <h3 class="list-group-item-heading">
                <%= food_option.description %>
              </h3>
            </div>

            <%= render 'layouts/common/icon_links/edit', link: edit_settings_food_option_path(food_option) %>
            <%= render 'layouts/common/icon_links/destroy', link: settings_food_option_path(food_option) %>
          </li>
        <% end.empty? %>
          <li class="list-group-item">
            <div class="media-body">
              <h3 class="list-group-item-heading">
                <%= t('core.empty') %>
              </h3>
            </div>
          </li>
        <% end %>
      </ul>

      <div id="list-action-buttons">
        <%= render 'layouts/common/buttons/new', link: new_settings_food_option_path %>
      </div>
    </div>
  </div>
</div>

app/views/web/settings/food_options/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <%= render 'layouts/common/header', title: FoodOption.model_name.human(count: 2), subtitle: t('core.actions.add') %>
      <%= render 'form' %>
    </div>
  </div>
</div>