config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, path: '', path_names: { sign_in: 'login' } , controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  devise_scope :user do
    get 'sign_out', to: 'users/sessions#destroy'
  end
  root :to => 'web/dashboards#index'

  scope module: :web do
    resources :dashboards, only: :index
    resources :diets, except: :show do
      resources :weight_movements, except: :show
    end
    namespace :settings do
      resources :food_options, except: :show
    end
  end
end

app/views/layouts/web/navigation/_sidebar.html.erb
<aside id="basicSidebar" class="pmd-sidebar  sidebar-default pmd-sidebar-slide-push pmd-sidebar-left pmd-sidebar-open bg-fill-darkblue sidebar-with-icons" role="navigation">
  <ul class="nav pmd-sidebar-nav">
    <!-- User info -->
    <li class="dropdown pmd-dropdown pmd-user-info visible-xs visible-md visible-sm visible-lg">
      <a aria-expanded="false" data-toggle="dropdown" class="btn-user dropdown-toggle media" data-sidebar="true" aria-expandedhref="javascript:void(0);">
        <div class="media-left">
          <%= image_tag("user-icon") %>
        </div>
        <div class="media-body media-middle"><%= current_user.email %></div>
        <div class="media-right media-middle"><i class="dic-more-vert dic"></i></div>
      </a>
      <ul class="dropdown-menu">
        <li><%= link_to "Sair", destroy_user_session_path %></li>
      </ul>
    </li><!-- End user info -->

    <%= render 'layouts/web/navigation/sidebar_menu_items' %>
  </ul>
</aside>

app/views/layouts/web/navigation/_sidebar_menu_items.html.erb
<li>
  <%= link_to dashboards_path, class: 'pmd-ripple-effect', target: "" do %>
    <i class="media-left media-middle material-icons pmd-sm">dashboard</i>
    <span class="media-body">Dashboard</span>
  <% end %>
</li>
<li>
  <%= link_to diets_path, class: 'pmd-ripple-effect', target: "" do %>
    <i class="media-left media-middle material-icons pmd-sm">assignment</i>
    <span class="media-body"><%= Diet.model_name.human(count: 2) %></span>
  <% end %>
</li>
<li class="dropdown pmd-dropdown">
  <a aria-expanded="false" data-toggle="dropdown" class="btn-user dropdown-toggle media" data-sidebar="true" href="javascript:void(0);">
    <i class="media-left media-middle material-icons pmd-sm">settings</i>
    <span class="media-body">Configurações</span>
    <div class="media-right media-bottom"><i class="dic-more-vert dic"></i></div>
  </a>
  <ul class="dropdown-menu">
    <li>
      <%= link_to settings_food_options_path, class: 'pmd-ripple-effect' do %>
        <%= FoodOption.model_name.human(count: 2) %>
      <% end %>
    </li>
  </ul>
</li>